#**Recommendation Systems in Machine Learning**

**Overview**

Recommendation systems (or recommender systems) are a subclass of information filtering systems that seek to predict the preference or rating a user would give to an item. They are widely used in various domains such as e-commerce, entertainment, social media, and content platforms to provide personalized content and improve user experience.

**Types of Recommendation Systems**

# **1.Content-Based Filtering**

**Overview**:

Content-based filtering recommends items to users based on the attributes or features of the items and a profile of the user's preferences. It uses the similarity between items' features and the user's preferences to make recommendations.

**Key Characteristics:**

 * Utilizes item features (e.g., genre, keywords, metadata).

* Recommends items similar to those liked by the user in the past.
* Doesn't require data on other users.
* Can provide explanations for recommendations based on item features.
* Examples: Recommending movies based on genre preferences, suggesting articles based on content similarity.

**Strengths:**



*     Doesn't suffer from cold-start problem for new users.

*   Can recommend niche or new items based on their features.
*  Provides transparent explanations for recommendations.




**Weaknesses:**

* Limited by the quality of item features.
* Tends to recommend similar items, which may lead to over-specialization.
* Struggles with providing diverse or serendipitous recommendations.

# **2. Collaborative Filtering**
**Overview:**

Collaborative filtering recommends items to users based on the preferences of other users. It identifies users with similar preferences and recommends items liked by those similar users.
Key Characteristics:

  * Utilizes user-item interactions or ratings.
  * Doesn't require item features; relies on user behavior.
  * Can capture complex patterns in user preferences.
  * Provides serendipitous recommendations based on similarities between users.
  * Examples: Recommending movies liked by users with similar movie preferences, suggesting products purchased by users with similar shopping behavior.

**Strengths:**

  * Can capture complex user preferences without explicit item features.
  * Provides serendipitous recommendations by identifying users with similar tastes.
  * Effective for recommending new items with limited data.

**Weaknesses:**

  * Faces the cold-start problem for new users with limited interaction data (The cold start problem in recommendation systems refers to the challenge of making accurate recommendations when there is insufficient data available. This happens when a new user joins the platform, there is little or no information about their preferences or When a new item is added to the catalog or When a recommendation system is newly deployed in a community or platform).
  * Suffers from sparsity of user-item interactions in large datasets.
  * Scalability challenges for large datasets due to high computational complexity.

# 3. **Matrix Factorization Methods**

**Overview:**

Matrix factorization methods decompose the user-item interaction matrix into latent factors and use them to predict user preferences or item characteristics.
Key Characteristics:

  * Represents users and items in a lower-dimensional latent space.
  * Learns latent factors from user-item interactions.
  * Can capture complex user preferences and item characteristics.
  * Examples: Singular Value Decomposition (SVD), Alternating Least Squares (ALS), matrix factorization with deep learning.

**Strengths:**

  * Captures complex patterns in user preferences and item characteristics.
  * Effective for handling sparse and high-dimensional datasets.
  * Enables efficient computation of recommendations in large-scale systems.

**Weaknesses:**

  * Requires a large amount of interaction data for accurate modeling.
  * Faces challenges with interpretability due to the latent factors.
  * May suffer from overfitting in the presence of noise or outliers.

#4. **Association Rule Learning**

**Overview:**

Association rule learning discovers frequent patterns, associations, or relationships among items in transactional datasets. It can be utilized in recommendation systems to generate item recommendations based on past purchasing behavior or interactions.
Key Characteristics:

  * Discovers associations or rules between items in transactional data.
  * Identifies frequent itemsets and generates association rules.
  * Often used in conjunction with other recommendation techniques.
  * Examples: Recommending products frequently purchased together, suggesting items based on historical transactional data.

**Strengths:**

  * Provides insights into associations between items in transactional data.
  * Effective for generating rules for cross-selling or upselling.
  * Can be combined with other recommendation techniques for improved accuracy.

**Weaknesses:**

  * May generate trivial or spurious rules in noisy datasets.
  * Limited to historical transactional data and may not capture evolving preferences.
  * Requires careful preprocessing and parameter tuning to produce meaningful rules.

In [2]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import svds

# Given transactions
transactions = [["Milk", "Bread", "Eggs", "Cheese", "Yogurt", "Jam"],
                ["Milk", "Bread", "Cheese", "Yogurt",  "Eggs"],
                ["Milk", "Bread", "Butter", "Juice", "Jam", "Eggs"],
                ["Milk", "Eggs", "Bread", "Cheese", "Juice"],
                ["Milk", "Bread", "Butter", "Cheese", "Jam", "Juice"],
                ["Milk", "Bread", "Eggs", "Jam", "Yogurt"]]

# Create a list of unique items
items = list(set(item for sublist in transactions for item in sublist))

# Create a dictionary to map items to indices
item_to_index = {item: index for index, item in enumerate(items)}
index_to_item = {index: item for item, index in item_to_index.items()}

# Create a transaction matrix
num_transactions = len(transactions)
num_items = len(items)
transaction_matrix = np.zeros((num_transactions, num_items), dtype=float)  # Change dtype to float

for i, transaction in enumerate(transactions):
    for item in transaction:
        j = item_to_index[item]
        transaction_matrix[i, j] = 1

# Convert the transaction matrix to a sparse matrix
sparse_transaction_matrix = csr_matrix(transaction_matrix)

# Perform Singular Value Decomposition (SVD)
k = min(num_transactions, num_items) - 1
U, Sigma, VT = svds(sparse_transaction_matrix, k=k)

# Generate recommendations
def recommend_items(user_id, U, Sigma, VT, top_n=3):
    user_vector = U[user_id, :]
    scores = np.dot(np.dot(user_vector, np.diag(Sigma)), VT)
    top_indices = np.argsort(scores)[::-1][:top_n]
    top_items = [index_to_item[index] for index in top_indices]
    return top_items

# Evaluate the model's performance (Example)
# Here, we'll evaluate the recommendation for the first user
user_id = 0
recommended_items = recommend_items(user_id, U, Sigma, VT)
print("Recommended items for user", user_id, ":", recommended_items)


Recommended items for user 0 : ['Bread', 'Milk', 'Yogurt']


**Evaluation**

To evaluate the recommendations made using the Singular Value Decomposition (SVD) model, we typically employ techniques such as **precision**, **recall**, and **F1-score**, or we may calculate metrics like Mean Average Precision **(MAP)**



**Precision**: Precision measures the proportion of recommended items that are relevant to the user out of all recommended items. It is calculated as the number of relevant recommendations divided by the total number of recommendations.
\begin{align}
        Precision = \frac{Number\ of\ relevant\ }{Total\ number\ of\ recommendations​}
    \end{align}


**Recall**: Recall measures the proportion of relevant items that are recommended out of all relevant items. It is calculated as the number of relevant recommendations divided by the total number of relevant items.

\begin{align}
        Recall = \frac{Number\ of\ relevant\ }{Total\ number\ of\ relevant\ items​}
    \end{align}

**F1-score:** F1-score is the harmonic mean of precision and recall. It provides a balance between precision and recall. It is calculated as:


\begin{align}
        F1-score = \frac{2×Precision×Recall }{Precision+Recall​}
    \end{align}

Mean Average Precision (MAP): MAP is a measure of the average precision for each user across all users. It is particularly useful for evaluating recommendation systems when the number of recommended items varies across users.

Here's how we can evaluate the model using precision:


1.       Prepare Ground Truth Data: Create a ground truth dataset containing

2.  Generate Recommendations: Use the SVD model to generate recommendations for each user.

3. Generate Recommendations: Use the SVD model to generate recommendations for each user.

4. Calculate Precision: For each user, compare the recommended items with the ground truth items and calculate precision.

5. Average Precision: Calculate the average precision across all users to get an overall measure of precision for the model.




In [7]:
ground_truth = {
    0: ["Milk", "Bread", "Cheese"],
    1: ["Bread", "Eggs", "Jam", "Yogurt"],
    # Add more ground truth data for other users if available
}

# Calculate precision for each user
precisions = []
for user_id, true_items in ground_truth.items():
    recommended_items = recommend_items(user_id, U, Sigma, VT)
    relevant_recommended = sum(1 for item in recommended_items if item in true_items)
    precision = relevant_recommended / len(recommended_items) if recommended_items else 0
    precisions.append(precision)

# Average precision across all users
avg_precision = sum(precisions) / len(precisions)

print("Average Precision:", avg_precision)

Average Precision: 0.6666666666666666


Assume the ground truth items for the user are: ['Milk', 'Bread', 'Eggs'].

And the recommendations provided by the model for the same user are: **['Milk', 'Eggs', 'Cheese', 'Yogurt']**.


# To calculate precision for this user:


  **Number of Relevant Recommendations:** Count the number of items in the recommendations list that are also in the ground truth list.
        Relevant recommendations: ['Milk', 'Eggs']
        Number of relevant recommendations: 2


**Total Number of Recommendations:** Count the total number of items in the recommendations list.
        Total number of recommendations: 4


**Calculate Precision:**
\begin{align}
        Precision = \frac{Number\ of\ relevant\ }{Total\ number\ of\ recommendations​}
    \end{align}

So, for this user, the precision is 0.5, meaning 50% of the recommended items are relevant to the user.

This process is repeated for each user, and the average precision across all users gives an overall measure of the model's performance.

Similarly, other metrices can also be calculated

In [8]:
import numpy as np
from scipy.sparse.linalg import svds

# Example user-movie rating matrix (5 users, 5 movies)
R = np.array([
    [5, 3, 0, 1, 4],
    [4, 0, 0, 1, 3],
    [1, 1, 0, 5, 0],
    [1, 0, 4, 4, 0],
    [0, 1, 5, 4, 0]
])

# Step 1: Normalize the matrix by subtracting the mean rating of each user
user_ratings_mean = np.mean(R, axis=1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

# Step 2: Perform SVD
U, sigma, Vt = svds(R_demeaned, k=2)

# Convert sigma to a diagonal matrix
sigma = np.diag(sigma)

# Step 3: Reconstruct the approximated matrix
R_approx = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

# Print the original and approximated matrices
print("Original Ratings Matrix:\n", R)
print("\nApproximated Ratings Matrix (after SVD and reconstruction):\n", R_approx)

# Step 4: Generate recommendations
# For example, let's recommend a movie for User 1 (index 0)
user_index = 0
# The original ratings of User 1
user_ratings = R[user_index, :]
# The predicted ratings of User 1
predicted_ratings = R_approx[user_index, :]

# Recommend movies that User 1 has not rated yet, sorted by predicted rating
recommendations = np.argsort(predicted_ratings)[::-1]  # Descending order

print("\nRecommendations for User 1:")
for movie_index in recommendations:
    if user_ratings[movie_index] == 0:
        print(f"Recommend Movie {movie_index + 1} with predicted rating {predicted_ratings[movie_index]:.2f}")

Original Ratings Matrix:
 [[5 3 0 1 4]
 [4 0 0 1 3]
 [1 1 0 5 0]
 [1 0 4 4 0]
 [0 1 5 4 0]]

Approximated Ratings Matrix (after SVD and reconstruction):
 [[ 4.71217085  2.98464243 -0.08949145  1.09184077  4.30083741]
 [ 3.26623539  1.60738472 -0.72631707  1.24036086  2.6123361 ]
 [ 1.49530381  0.16670693  0.41411635  4.83870479  0.08516812]
 [ 0.25261365  1.04113813  3.44055136  4.24256732  0.02312954]
 [-0.2754878   1.41985923  4.78286572  4.08954728 -0.01678443]]

Recommendations for User 1:
Recommend Movie 3 with predicted rating -0.09


In [16]:
# Step 4: Generate recommendations
# For example, let's recommend a movie for User 1 (index 0)
user_index = 0
# The original ratings of User 1
user_ratings = R[user_index, :]
# The predicted ratings of User 1
predicted_ratings = R_approx[user_index, :]

# Recommend movies that User 1 has not rated yet, sorted by predicted rating
positive_recommendations = [(i, rating) for i, rating in enumerate(predicted_ratings) if user_ratings[i] == 0 and rating > 0]
positive_recommendations.sort(key=lambda x: x[1], reverse=True)

print("\nRecommendations for User 1:")
for movie_index, rating in positive_recommendations:
    print(f"Recommend Movie {movie_index + 1} with predicted rating {rating:.2f}")



Recommendations for User 1:


In [ ]:
# Generate MovieLens data and use SVD to generate movie recommendations